version: "3.9"
services:
  nginx:
    image: nginx:1.23.2
    build:
      context: .
      dockerfile: ./deployment/nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    restart: on-failure
    depends_on:
      - gunicorn

  gunicorn:
    image: wallit-latest
    hostname: gunicorn
    build: .
    ports:
      - "5000:5000"
    env_file:
      - deployment/gunicorn/.gunicornenv
    restart: on-failure
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    ports:
      - "5433:5432"
    env_file:
      - deployment/postgres/.postgresenv
    restart: on-failure
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
