# version: '3'
services:
  wallit:
    image: wallit-latest
    build: .
    ports:
      - "8000:5000"
    environment:
      CURRENCYSCOOP_API_KEY: 39c83a7c50bb795501ee384a76c18cac
      SQLALCHEMY_DATABASE_URI: postgresql://admin:password@postgres/wallit
    depends_on:
      - postgres
  postgres:
    image: postgres:14
    # ports:
      # - 5433:5432 host:container
    environment:
      POSTGRES_DB: wallit
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-db:/var/lib/postgresql/data
volumes:
  postgres-db:
    # driver: local
