app = "wallit"
primary_region = "waw"
kill_signal = "SIGTERM"
kill_timeout = "5s"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false

  [http_service.concurrency]
    type = "requests"
    hard_limit = 300
    soft_limit = 250

  [[http_service.checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "30s"
    method = "GET"
    path = "/welcome"
    
[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
