"""added categories TABLE, DELETE CASCADE on transactions

Revision ID: 28e803e18927
Revises: 874b0ebea9e4
Create Date: 2022-06-24 17:10:45.970115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "28e803e18927"
down_revision = "874b0ebea9e4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("userId", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["userId"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_categories_name"), "categories", ["name"], unique=False)
    op.drop_constraint("transactions_userId_fkey", "transactions", type_="foreignkey")
    op.create_foreign_key(
        None, "transactions", "users", ["userId"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "transactions", type_="foreignkey")
    op.create_foreign_key(
        "transactions_userId_fkey", "transactions", "users", ["userId"], ["id"]
    )
    op.drop_index(op.f("ix_categories_name"), table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
