"""new structure of transactions table

Revision ID: 3f0d65263524
Revises: 070705a0d556
Create Date: 2022-06-30 21:15:37.906410

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "3f0d65263524"
down_revision = "070705a0d556"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transactions", sa.Column("main_amount", sa.Float(), nullable=False))
    op.add_column("transactions", sa.Column("base_amount", sa.Float(), nullable=True))
    op.add_column(
        "transactions", sa.Column("base_currency", sa.String(length=3), nullable=True)
    )
    op.add_column(
        "users", sa.Column("main_currency", sa.String(length=3), nullable=False)
    )
    op.drop_index("ix_transactions_amount", table_name="transactions")
    op.drop_index("ix_transactions_currency", table_name="transactions")
    op.create_index(
        op.f("ix_transactions_main_amount"),
        "transactions",
        ["main_amount"],
        unique=False,
    )
    op.drop_column("transactions", "amount")
    op.drop_column("transactions", "src_amount")
    op.drop_column("transactions", "currency")
    op.drop_column("transactions", "src_currency")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "main_currency")
    op.add_column(
        "transactions",
        sa.Column("src_currency", sa.Text(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "transactions",
        sa.Column("currency", sa.Text(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "transactions",
        sa.Column(
            "src_amount",
            sa.Float(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "transactions",
        sa.Column(
            "amount",
            sa.Float(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_index(op.f("ix_transactions_main_amount"), table_name="transactions")
    op.create_index(
        "ix_transactions_currency", "transactions", ["currency"], unique=False
    )
    op.create_index("ix_transactions_amount", "transactions", ["amount"], unique=False)
    op.drop_column("transactions", "base_currency")
    op.drop_column("transactions", "base_amount")
    op.drop_column("transactions", "main_amount")
    # ### end Alembic commands ###
