"""created db

Revision ID: 874b0ebea9e4
Revises:
Create Date: 2022-06-19 18:13:45.553829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "874b0ebea9e4"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "banks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_banks_name"), "banks", ["name"], unique=True)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("passwordHash", sa.Text(), nullable=False),
        sa.Column("firstName", sa.Text(), nullable=True),
        sa.Column("lastName", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("info", sa.Text(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("currency", sa.Text(), nullable=False),
        sa.Column("srcAmount", sa.Float(), nullable=True),
        sa.Column("srcCurrency", sa.Text(), nullable=True),
        sa.Column("transactionDate", sa.DateTime(), nullable=False),
        sa.Column("place", sa.Text(), nullable=True),
        sa.Column("category", sa.Text(), nullable=True),
        sa.Column("userId", sa.Integer(), nullable=False),
        sa.Column("bankId", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["bankId"],
            ["banks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["userId"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_transactions_amount"), "transactions", ["amount"], unique=False
    )
    op.create_index(
        op.f("ix_transactions_category"), "transactions", ["category"], unique=False
    )
    op.create_index(
        op.f("ix_transactions_currency"), "transactions", ["currency"], unique=False
    )
    op.create_index(
        op.f("ix_transactions_info"), "transactions", ["info"], unique=False
    )
    op.create_index(
        op.f("ix_transactions_transactionDate"),
        "transactions",
        ["transactionDate"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transactions_transactionDate"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_info"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_currency"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_category"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_amount"), table_name="transactions")
    op.drop_table("transactions")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_banks_name"), table_name="banks")
    op.drop_table("banks")
    # ### end Alembic commands ###
