"""NOT NULL bank const. deleted from transactions

Revision ID: 8cb831dd02e6
Revises: 7d1601d1a120
Create Date: 2022-07-28 12:07:34.984205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8cb831dd02e6"
down_revision = "7d1601d1a120"
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transactions") as batch_op:
        batch_op.alter_column("bank_id", existing_type=sa.INTEGER(), nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transactions") as batch_op:
        batch_op.alter_column("bank_id", existing_type=sa.INTEGER(), nullable=False)
    ### end Alembic commands ###
