"""unique constraint on Category.name


Revision ID: a91b8a63b3e5
Revises: d81eefc58af9
Create Date: 2022-07-01 20:08:14.911875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a91b8a63b3e5"
down_revision = "d81eefc58af9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_categories_name", table_name="categories")
    op.create_index(op.f("ix_categories_name"), "categories", ["name"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_categories_name"), table_name="categories")
    op.create_index("ix_categories_name", "categories", ["name"], unique=False)
    # ### end Alembic commands ###
