"""restructured transaction, main_currency moved to user

Revision ID: d81eefc58af9
Revises: 3f0d65263524
Create Date: 2022-06-30 21:21:42.513411

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d81eefc58af9"
down_revision = "3f0d65263524"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "transactions",
        "base_amount",
        existing_type=postgresql.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "transactions",
        "base_currency",
        existing_type=sa.VARCHAR(length=3),
        nullable=False,
    )
    op.create_index(
        op.f("ix_transactions_base_amount"),
        "transactions",
        ["base_amount"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transactions_base_currency"),
        "transactions",
        ["base_currency"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transactions_base_currency"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_base_amount"), table_name="transactions")
    op.alter_column(
        "transactions",
        "base_currency",
        existing_type=sa.VARCHAR(length=3),
        nullable=True,
    )
    op.alter_column(
        "transactions",
        "base_amount",
        existing_type=postgresql.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    # ### end Alembic commands ###
