"""Added ForeignKey(category) to transactions

Revision ID: df13f865dc70
Revises: 28e803e18927
Create Date: 2022-06-24 18:12:38.887854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "df13f865dc70"
down_revision = "28e803e18927"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transactions", sa.Column("categoryId", sa.Integer(), nullable=True))
    op.drop_index("ix_transactions_category", table_name="transactions")
    op.create_index(
        op.f("ix_transactions_categoryId"), "transactions", ["categoryId"], unique=False
    )
    op.create_foreign_key(None, "transactions", "categories", ["categoryId"], ["id"])
    op.drop_column("transactions", "category")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions",
        sa.Column("category", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "transactions", type_="foreignkey")
    op.drop_index(op.f("ix_transactions_categoryId"), table_name="transactions")
    op.create_index(
        "ix_transactions_category", "transactions", ["category"], unique=False
    )
    op.drop_column("transactions", "categoryId")
    # ### end Alembic commands ###
